<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="327162" started-at="2024-03-02T15:57:46Z" finished-at="2024-03-02T16:03:13Z">
    <groups>
    </groups>
    <test name="ChromeTest" duration-ms="327162" started-at="2024-03-02T15:57:46Z" finished-at="2024-03-02T16:03:13Z">
      <class name="qa.tests.LoginSampleTests">
        <test-method status="PASS" signature="beforeTestMethod()[pri:0, instance:qa.tests.LoginSampleTests@77caeb3e]" name="beforeTestMethod" is-config="true" duration-ms="368" started-at="2024-03-02T21:27:46Z" finished-at="2024-03-02T21:27:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestMethod -->
        <test-method status="PASS" signature="setUpDriver(java.lang.String, java.lang.reflect.Method)[pri:0, instance:qa.tests.LoginSampleTests@77caeb3e]" name="setUpDriver" is-config="true" duration-ms="30456" started-at="2024-03-02T21:27:46Z" finished-at="2024-03-02T21:28:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void qa.tests.LoginSampleTests.enterLoginCredentials()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpDriver -->
        <test-method status="FAIL" signature="enterLoginCredentials()[pri:0, instance:qa.tests.LoginSampleTests@77caeb3e]" name="enterLoginCredentials" duration-ms="13109" started-at="2024-03-02T21:28:17Z" finished-at="2024-03-02T21:28:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element not present expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element not present expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at pageEvents.LoginPageEvents.verifyIfLoginPageIsLoaded(LoginPageEvents.java:14)
	at qa.tests.LoginSampleTests.enterLoginCredentials(LoginSampleTests.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterLoginCredentials -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:qa.tests.LoginSampleTests@77caeb3e]" name="afterMethod" is-config="true" duration-ms="1179" started-at="2024-03-02T21:28:30Z" finished-at="2024-03-02T21:28:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=enterLoginCredentials status=FAILURE method=LoginSampleTests.enterLoginCredentials()[pri:0, instance:qa.tests.LoginSampleTests@77caeb3e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="setUpDriver(java.lang.String, java.lang.reflect.Method)[pri:0, instance:qa.tests.LoginSampleTests@77caeb3e]" name="setUpDriver" is-config="true" duration-ms="229635" started-at="2024-03-02T21:28:31Z" finished-at="2024-03-02T21:32:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void qa.tests.LoginSampleTests.enterLoginCredentials()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpDriver -->
        <test-method status="FAIL" signature="enterLoginCredentials()[pri:0, instance:qa.tests.LoginSampleTests@77caeb3e]" name="enterLoginCredentials" duration-ms="49345" started-at="2024-03-02T21:32:21Z" finished-at="2024-03-02T21:33:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element not present expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element not present expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at pageEvents.LoginPageEvents.verifyIfLoginPageIsLoaded(LoginPageEvents.java:14)
	at qa.tests.LoginSampleTests.enterLoginCredentials(LoginSampleTests.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterLoginCredentials -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:qa.tests.LoginSampleTests@77caeb3e]" name="afterMethod" is-config="true" duration-ms="1454" started-at="2024-03-02T21:33:10Z" finished-at="2024-03-02T21:33:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=enterLoginCredentials status=FAILURE method=LoginSampleTests.enterLoginCredentials()[pri:0, instance:qa.tests.LoginSampleTests@77caeb3e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:qa.tests.LoginSampleTests@77caeb3e]" name="afterTest" is-config="true" duration-ms="1015" started-at="2024-03-02T21:33:12Z" finished-at="2024-03-02T21:33:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- qa.tests.LoginSampleTests -->
    </test> <!-- ChromeTest -->
  </suite> <!-- Suite -->
</testng-results>
